// Auto-generated by scripts/import-tw314-native.mjs
export const TW314_KATEX_MACROS = {
  "\\identity": "\\mathrm{id}",
  "\\notdivide": "{\\not{\\mid}}",
  "\\notsubset": "\\not\\subset",
  "\\lcm": "\\operatorname{lcm}",
  "\\gf": "\\operatorname{GF}",
  "\\inn": "\\operatorname{Inn}",
  "\\aut": "\\operatorname{Aut}",
  "\\Hom": "\\operatorname{Hom}",
  "\\cis": "\\operatorname{cis}",
  "\\chr": "\\operatorname{char}",
  "\\Null": "\\operatorname{Null}",
  "\\lt": "<",
  "\\gt": ">",
  "\\amp": "&"
};
