// Auto-generated by scripts/import-tw314-native.mjs
export const TW314_DEFAULT_SLUG = "frontmatter";
export const TW314_PAGES = [
  {
    "slug": "frontmatter",
    "order": 1,
    "title": "Front Matter"
  },
  {
    "slug": "preface",
    "order": 2,
    "title": "Preface"
  },
  {
    "slug": "part-graph",
    "order": 3,
    "title": "Graph Theory"
  },
  {
    "slug": "graphs",
    "order": 4,
    "title": "An introduction to graphs"
  },
  {
    "slug": "section-notation",
    "order": 5,
    "title": "Basic notation"
  },
  {
    "slug": "section-first-theorem",
    "order": 6,
    "title": "The first theorem of graph theory"
  },
  {
    "slug": "section-subgraph",
    "order": 7,
    "title": "Subgraphs"
  },
  {
    "slug": "section-connectedness",
    "order": 8,
    "title": "Paths and connectivity"
  },
  {
    "slug": "section-isomorphism",
    "order": 9,
    "title": "Equality and isomorphism"
  },
  {
    "slug": "section-graphical",
    "order": 10,
    "title": "Graphical sequences"
  },
  {
    "slug": "section-special-graphs",
    "order": 11,
    "title": "Special graphs and some constructs"
  },
  {
    "slug": "section-trees",
    "order": 12,
    "title": "Trees"
  },
  {
    "slug": "planar",
    "order": 13,
    "title": "Planar graphs"
  },
  {
    "slug": "section-embeddings",
    "order": 14,
    "title": "Embeddings and plane graphs"
  },
  {
    "slug": "section-euler",
    "order": 15,
    "title": "Euler's theorem"
  },
  {
    "slug": "section-maximal-planar",
    "order": 16,
    "title": "Maximal planar graphs"
  },
  {
    "slug": "section-polyhedra",
    "order": 17,
    "title": "Polyhedra"
  },
  {
    "slug": "section-maximal",
    "order": 18,
    "title": "A characterization of planar graphs"
  },
  {
    "slug": "section-algorithm",
    "order": 19,
    "title": "A planarity algorithm"
  },
  {
    "slug": "colour",
    "order": 20,
    "title": "Graph colourings"
  },
  {
    "slug": "section-chromatic",
    "order": 21,
    "title": "Chromatic numbers"
  },
  {
    "slug": "section-bounds",
    "order": 22,
    "title": "Bounds on the chromatic number"
  },
  {
    "slug": "section-4colour",
    "order": 23,
    "title": "The four-colour problem"
  },
  {
    "slug": "part-crypto",
    "order": 24,
    "title": "Cryptography"
  },
  {
    "slug": "crypto",
    "order": 25,
    "title": "An introduction to cryptography"
  },
  {
    "slug": "section-crypto-notation",
    "order": 26,
    "title": "What is cryptography?"
  },
  {
    "slug": "section-crypto-symmetric",
    "order": 27,
    "title": "Symmetric-key primitives"
  },
  {
    "slug": "section-crypto-public",
    "order": 28,
    "title": "Public-key primitives"
  },
  {
    "slug": "crypto_algebra",
    "order": 29,
    "title": "Important algebraic concepts"
  },
  {
    "slug": "section-crypto-mod",
    "order": 30,
    "title": "Modular arithmetic"
  },
  {
    "slug": "section-crypto-group",
    "order": 31,
    "title": "Groups"
  },
  {
    "slug": "section-crypto-rings",
    "order": 32,
    "title": "Rings"
  },
  {
    "slug": "section-crypto-field",
    "order": 33,
    "title": "Fields"
  },
  {
    "slug": "crypto_key",
    "order": 34,
    "title": "Key establishment"
  },
  {
    "slug": "section-exponent",
    "order": 35,
    "title": "Exponentiation"
  },
  {
    "slug": "section-crypto-DH",
    "order": 36,
    "title": "Diffie-Hellman"
  },
  {
    "slug": "section-crypto-inverse",
    "order": 37,
    "title": "Inverses in finite groups"
  },
  {
    "slug": "section-crypto-log-alg",
    "order": 38,
    "title": "An algorithm for computing discrete logartihms"
  },
  {
    "slug": "crypto_rsa",
    "order": 39,
    "title": "RSA encryption"
  },
  {
    "slug": "section-crypto-number",
    "order": 40,
    "title": "Number theory"
  },
  {
    "slug": "section-crypto-rsa",
    "order": 41,
    "title": "The RSA system"
  },
  {
    "slug": "part-coding",
    "order": 42,
    "title": "Coding theory"
  },
  {
    "slug": "coding_error",
    "order": 43,
    "title": "Error-correcting codes"
  },
  {
    "slug": "section-coding-intro",
    "order": 44,
    "title": "Introduction"
  },
  {
    "slug": "section-coding-channel",
    "order": 45,
    "title": "A digital communication system"
  },
  {
    "slug": "section-coding-block",
    "order": 46,
    "title": "Block codes"
  },
  {
    "slug": "section-coding-hamming",
    "order": 47,
    "title": "Hamming distances"
  },
  {
    "slug": "section-coding-neighbour",
    "order": 48,
    "title": "Nearest neighbour decoding"
  },
  {
    "slug": "section-coding-minimum",
    "order": 49,
    "title": "Minimum distance"
  },
  {
    "slug": "section-coding-equiv",
    "order": 50,
    "title": "Equivalent codes"
  },
  {
    "slug": "section-coding-parameters",
    "order": 51,
    "title": "Optimising the parameters \\(n\\text{,}\\) \\(M\\) and \\(d\\)"
  },
  {
    "slug": "section-coding-hammingbound",
    "order": 52,
    "title": "The Hamming bound"
  },
  {
    "slug": "section-coding-perfect",
    "order": 53,
    "title": "Perfect codes"
  },
  {
    "slug": "coding_linear",
    "order": 54,
    "title": "Linear codes"
  },
  {
    "slug": "section-coding-vector",
    "order": 55,
    "title": "Vectorspaces"
  },
  {
    "slug": "section-coding-linear",
    "order": 56,
    "title": "Introduction to linear codes"
  },
  {
    "slug": "section-coding-encode-linear",
    "order": 57,
    "title": "Encoding with a linear code"
  },
  {
    "slug": "section-coding-cosets",
    "order": 58,
    "title": "Cosets"
  },
  {
    "slug": "section-coding-decode",
    "order": 59,
    "title": "Decoding with a linear code"
  },
  {
    "slug": "section-coding-dual",
    "order": 60,
    "title": "Dual codes"
  },
  {
    "slug": "section-coding-syndrome",
    "order": 61,
    "title": "Syndrome decoding"
  },
  {
    "slug": "coding_hamming",
    "order": 62,
    "title": "Hamming codes"
  },
  {
    "slug": "section-coding-ham-intro",
    "order": 63,
    "title": "Introduction"
  },
  {
    "slug": "section-coding-ham-decode",
    "order": 64,
    "title": "Decoding with a binary Hamming code"
  },
  {
    "slug": "section-coding-ham-extend",
    "order": 65,
    "title": "The extended binary Hamming code"
  },
  {
    "slug": "section-coding-fund",
    "order": 66,
    "title": "A fundamental theorem"
  },
  {
    "slug": "section-coding-qham",
    "order": 67,
    "title": "\\(q\\)-ary Hamming codes"
  },
  {
    "slug": "section-coding-qham-decode",
    "order": 68,
    "title": "Decoding with a \\(q\\)-ary Hamming code"
  },
  {
    "slug": "coding_cyclic",
    "order": 69,
    "title": "Cyclic codes"
  },
  {
    "slug": "section-coding-cyclic-intro",
    "order": 70,
    "title": "Introduction"
  },
  {
    "slug": "section-coding-ring",
    "order": 71,
    "title": "The ring of polynomials modulo \\(f(x)\\)"
  },
  {
    "slug": "section-coding-cyclic-check",
    "order": 72,
    "title": "The check polynomial and the parity-check matrix of a cyclic code"
  },
  {
    "slug": "discrete-book",
    "order": 73,
    "title": "Applied Mathematics 314"
  }
];
export const TW314_TOC = {
  "preface": [
    {
      "slug": "frontmatter",
      "codenumber": "",
      "title": "Front Matter",
      "sections": [
        {
          "slug": "preface",
          "title": "Preface"
        }
      ]
    }
  ],
  "parts": [
    {
      "slug": "part-graph",
      "codenumber": "I",
      "title": "Graph Theory",
      "chapters": [
        {
          "slug": "graphs",
          "codenumber": "1",
          "title": "An introduction to graphs",
          "sections": [
            {
              "slug": "section-notation",
              "title": "Basic notation"
            },
            {
              "slug": "section-first-theorem",
              "title": "The first theorem of graph theory"
            },
            {
              "slug": "section-subgraph",
              "title": "Subgraphs"
            },
            {
              "slug": "section-connectedness",
              "title": "Paths and connectivity"
            },
            {
              "slug": "section-isomorphism",
              "title": "Equality and isomorphism"
            },
            {
              "slug": "section-graphical",
              "title": "Graphical sequences"
            },
            {
              "slug": "section-special-graphs",
              "title": "Special graphs and some constructs"
            },
            {
              "slug": "section-trees",
              "title": "Trees"
            }
          ]
        },
        {
          "slug": "planar",
          "codenumber": "2",
          "title": "Planar graphs",
          "sections": [
            {
              "slug": "section-embeddings",
              "title": "Embeddings and plane graphs"
            },
            {
              "slug": "section-euler",
              "title": "Euler's theorem"
            },
            {
              "slug": "section-maximal-planar",
              "title": "Maximal planar graphs"
            },
            {
              "slug": "section-polyhedra",
              "title": "Polyhedra"
            },
            {
              "slug": "section-maximal",
              "title": "A characterization of planar graphs"
            },
            {
              "slug": "section-algorithm",
              "title": "A planarity algorithm"
            }
          ]
        },
        {
          "slug": "colour",
          "codenumber": "3",
          "title": "Graph colourings",
          "sections": [
            {
              "slug": "section-chromatic",
              "title": "Chromatic numbers"
            },
            {
              "slug": "section-bounds",
              "title": "Bounds on the chromatic number"
            },
            {
              "slug": "section-4colour",
              "title": "The four-colour problem"
            }
          ]
        }
      ]
    },
    {
      "slug": "part-crypto",
      "codenumber": "II",
      "title": "Cryptography",
      "chapters": [
        {
          "slug": "crypto",
          "codenumber": "4",
          "title": "An introduction to cryptography",
          "sections": [
            {
              "slug": "section-crypto-notation",
              "title": "What is cryptography?"
            },
            {
              "slug": "section-crypto-symmetric",
              "title": "Symmetric-key primitives"
            },
            {
              "slug": "section-crypto-public",
              "title": "Public-key primitives"
            }
          ]
        },
        {
          "slug": "crypto_algebra",
          "codenumber": "5",
          "title": "Important algebraic concepts",
          "sections": [
            {
              "slug": "section-crypto-mod",
              "title": "Modular arithmetic"
            },
            {
              "slug": "section-crypto-group",
              "title": "Groups"
            },
            {
              "slug": "section-crypto-rings",
              "title": "Rings"
            },
            {
              "slug": "section-crypto-field",
              "title": "Fields"
            }
          ]
        },
        {
          "slug": "crypto_key",
          "codenumber": "6",
          "title": "Key establishment",
          "sections": [
            {
              "slug": "section-exponent",
              "title": "Exponentiation"
            },
            {
              "slug": "section-crypto-DH",
              "title": "Diffie-Hellman"
            },
            {
              "slug": "section-crypto-inverse",
              "title": "Inverses in finite groups"
            },
            {
              "slug": "section-crypto-log-alg",
              "title": "An algorithm for computing discrete logartihms"
            }
          ]
        },
        {
          "slug": "crypto_rsa",
          "codenumber": "7",
          "title": "RSA encryption",
          "sections": [
            {
              "slug": "section-crypto-number",
              "title": "Number theory"
            },
            {
              "slug": "section-crypto-rsa",
              "title": "The RSA system"
            }
          ]
        }
      ]
    },
    {
      "slug": "part-coding",
      "codenumber": "III",
      "title": "Coding theory",
      "chapters": [
        {
          "slug": "coding_error",
          "codenumber": "8",
          "title": "Error-correcting codes",
          "sections": [
            {
              "slug": "section-coding-intro",
              "title": "Introduction"
            },
            {
              "slug": "section-coding-channel",
              "title": "A digital communication system"
            },
            {
              "slug": "section-coding-block",
              "title": "Block codes"
            },
            {
              "slug": "section-coding-hamming",
              "title": "Hamming distances"
            },
            {
              "slug": "section-coding-neighbour",
              "title": "Nearest neighbour decoding"
            },
            {
              "slug": "section-coding-minimum",
              "title": "Minimum distance"
            },
            {
              "slug": "section-coding-equiv",
              "title": "Equivalent codes"
            },
            {
              "slug": "section-coding-parameters",
              "title": "Optimising the parameters \\(n\\text{,}\\) \\(M\\) and \\(d\\)"
            },
            {
              "slug": "section-coding-hammingbound",
              "title": "The Hamming bound"
            },
            {
              "slug": "section-coding-perfect",
              "title": "Perfect codes"
            }
          ]
        },
        {
          "slug": "coding_linear",
          "codenumber": "9",
          "title": "Linear codes",
          "sections": [
            {
              "slug": "section-coding-vector",
              "title": "Vectorspaces"
            },
            {
              "slug": "section-coding-linear",
              "title": "Introduction to linear codes"
            },
            {
              "slug": "section-coding-encode-linear",
              "title": "Encoding with a linear code"
            },
            {
              "slug": "section-coding-cosets",
              "title": "Cosets"
            },
            {
              "slug": "section-coding-decode",
              "title": "Decoding with a linear code"
            },
            {
              "slug": "section-coding-dual",
              "title": "Dual codes"
            },
            {
              "slug": "section-coding-syndrome",
              "title": "Syndrome decoding"
            }
          ]
        },
        {
          "slug": "coding_hamming",
          "codenumber": "10",
          "title": "Hamming codes",
          "sections": [
            {
              "slug": "section-coding-ham-intro",
              "title": "Introduction"
            },
            {
              "slug": "section-coding-ham-decode",
              "title": "Decoding with a binary Hamming code"
            },
            {
              "slug": "section-coding-ham-extend",
              "title": "The extended binary Hamming code"
            },
            {
              "slug": "section-coding-fund",
              "title": "A fundamental theorem"
            },
            {
              "slug": "section-coding-qham",
              "title": "\\(q\\)-ary Hamming codes"
            },
            {
              "slug": "section-coding-qham-decode",
              "title": "Decoding with a \\(q\\)-ary Hamming code"
            }
          ]
        },
        {
          "slug": "coding_cyclic",
          "codenumber": "11",
          "title": "Cyclic codes",
          "sections": [
            {
              "slug": "section-coding-cyclic-intro",
              "title": "Introduction"
            },
            {
              "slug": "section-coding-ring",
              "title": "The ring of polynomials modulo \\(f(x)\\)"
            },
            {
              "slug": "section-coding-cyclic-check",
              "title": "The check polynomial and the parity-check matrix of a cyclic code"
            }
          ]
        }
      ]
    }
  ]
};

export function toTw314Href(slug = TW314_DEFAULT_SLUG) {
  const normalized = String(slug ?? "").trim();
  if (!normalized || normalized === TW314_DEFAULT_SLUG) {
    return "/tw314";
  }
  return `/tw314/${normalized}`;
}
