import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const contentRoot = path.join(projectRoot, 'content');
const outputPath = path.join(projectRoot, 'src', 'generated', 'content-artifacts.js');

marked.setOptions({
  gfm: true,
  breaks: false,
  mangle: false,
  headerIds: false,
});

function trim(value) {
  return value.replace(/^\/+|\/+$/g, '');
}

function titleFromPath(relativePath) {
  const withoutExtension = relativePath.replace(/\.md$/i, '');
  const filename = withoutExtension.split('/').at(-1) ?? 'content';
  if (filename === 'index') {
    const parent = withoutExtension.split('/').at(-2) ?? 'home';
    return parent.charAt(0).toUpperCase() + parent.slice(1);
  }

  return filename
    .split('-')
    .map((chunk) => chunk.charAt(0).toUpperCase() + chunk.slice(1))
    .join(' ');
}

function parseFrontmatter(rawMarkdown) {
  if (!rawMarkdown.startsWith('---\n')) {
    return {
      metadata: {},
      body: rawMarkdown,
    };
  }

  const closingMarkerIndex = rawMarkdown.indexOf('\n---\n', 4);
  if (closingMarkerIndex === -1) {
    return {
      metadata: {},
      body: rawMarkdown,
    };
  }

  const frontmatterBlock = rawMarkdown.slice(4, closingMarkerIndex).trim();
  const body = rawMarkdown.slice(closingMarkerIndex + 5);
  const metadata = {};

  for (const line of frontmatterBlock.split('\n')) {
    const separatorIndex = line.indexOf(':');
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    metadata[key] = value;
  }

  return {
    metadata,
    body,
  };
}

async function collectMarkdownFiles(dirPath) {
  const directoryEntries = await readdir(dirPath, { withFileTypes: true });
  const discovered = [];

  for (const entry of directoryEntries) {
    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      discovered.push(...(await collectMarkdownFiles(fullPath)));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith('.md')) {
      discovered.push(fullPath);
    }
  }

  return discovered.sort();
}

function toArtifact(relativePath, rawMarkdown) {
  const unixRelativePath = relativePath.split(path.sep).join('/');
  const withoutExtension = unixRelativePath.replace(/\.md$/i, '');
  const pathSegments = withoutExtension.split('/').filter(Boolean);
  const appId = pathSegments[0] ?? 'home';

  const subrouteSegments = [...pathSegments.slice(1)];
  if (subrouteSegments.at(-1) === 'index') {
    subrouteSegments.pop();
  }

  const subroute = trim(subrouteSegments.join('/'));
  const key = pathSegments.join('.');

  const { metadata, body } = parseFrontmatter(rawMarkdown);
  const title = metadata.title ?? titleFromPath(unixRelativePath);
  const excerpt = metadata.excerpt ?? '';

  return {
    key,
    appId,
    subroute,
    title,
    excerpt,
    html: marked.parse(body),
  };
}

async function buildArtifacts() {
  const markdownFiles = await collectMarkdownFiles(contentRoot);
  const artifacts = [];

  for (const filePath of markdownFiles) {
    const relativePath = path.relative(contentRoot, filePath);
    const rawMarkdown = await readFile(filePath, 'utf8');
    artifacts.push(toArtifact(relativePath, rawMarkdown));
  }

  artifacts.sort((left, right) => left.key.localeCompare(right.key));

  const artifactMap = Object.fromEntries(artifacts.map((artifact) => [artifact.key, artifact]));

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    [
      '// This file is auto-generated by scripts/build-content.mjs',
      '// Do not edit by hand.',
      `export const CONTENT_ARTIFACTS = ${JSON.stringify(artifactMap, null, 2)};`,
      '',
    ].join('\n'),
    'utf8',
  );

  console.log(`Generated ${artifacts.length} content artifacts -> ${path.relative(projectRoot, outputPath)}`);
}

buildArtifacts().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
